

spring.bserver:
error:
include-message: always
include-binding-errors: always

spring:
datasource: root
password: VR&&jt(45)%
url: jdbc:mysql://localhost:3306/taxcalculator
username:
jpa:
hibernate:
ddl-auto: create-drop
properties:

dialect: org.hibernate.dialect.PostgreSQLDialect
format_sql: true
show-sql: true

